# Generated by Django 5.0.4 on 2024-04-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя капитана')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия капитана')),
                ('experience', models.IntegerField(max_length=4, verbose_name='Опыт пилотирования(в годах)')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название компании')),
                ('country', models.CharField(max_length=30, verbose_name='Страна компании')),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('count_pass', models.IntegerField(max_length=4, verbose_name='Колличество пассажиров')),
                ('wight', models.IntegerField(max_length=10, verbose_name='Масса самолета в кг')),
                ('fuel_reserve', models.IntegerField(max_length=10, verbose_name='Запас топлива в км')),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airburg_app.capitan', verbose_name='Капитан')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airburg_app.company', verbose_name='Компания')),
            ],
        ),
    ]
